version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '03:00'
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.42"
  - dependency-name: "@types/vscode"
    versions:
    - "> 1.40.0"
