language: node_js

sudo: true

node_js:
  - 9
  - 8
  - 6

os:
  - linux

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  
cache:
  yarn: true
  

