language: node_js
services: xvfb

os:
  - linux
  - osx

node_js:
  - 12 # lts, and the version vscode-stable currently uses (via electron)

addons:
  apt:
    packages:
    # resolves a warning while running e2e. needed by electron (used by node-keytar).
    - libsecret-1-dev

# Travis uses older yarn on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH=$HOME/.yarn/bin:$PATH
