language: node_js

os:
  - linux
#  - osx

node_js:
  - 10 # lts, and the version vscode-stable currently uses (via electron)

cache:
  yarn: true

# Travis uses yarn@1.3.2 on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
