language: node_js

sudo: false

node_js:
  - 9
  - 8
  - 6

os:
  - linux

addons:
  apt:
    packages:
      - libsecret-1-dev
      
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

cache:
  yarn: true