environment:
  nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  # run tests
  - yarn test

build: off

cache:
  - "%LOCALAPPDATA%\\Yarn"